### ISSUE TITLE
Missing stops and couplers

### ISSUE THREAD

**Issue by William-Purvis** [larspalo/GOODF#15]
I started with a simplified version of the Billerbeck demo, using Andrew Halls software to extract from the original Hauptwerk demo.
I wanted to modify the GUI, and decided to use GOODF to replace one of the default stops with an image file. I then tried to compare this with the original ODF, but GOODF had re-organised the ordering of everything. In order to have something to compare against I
read in the original file, then, without changing anything wrote it out again. This allowed me to see what GOODF had actually changed,
which seemed OK. I then went on to replaced all the stops and couplers with my own images. This loaded and appeared to have
achieved my goal. However, when I tried to use the organ there was no sound. By going through the two ODFs side by side, I found that all the Stop and Coupler entries had been discarded.
I've uploaded the ODF, but had to rename it to be .txt to keep Firefox happy.
Simply use GOODF to load the file, then save as an alternative name and search for [STOP or [COUPLER.
There should be 34 [STOP*]s and 6 [COUPLER*]s.
GOODF was built using the version on github yesterday (12/04/2023).

[Penketh1.txt](https://github.com/larspalo/GOODF/files/11224638/Penketh1.txt)

**Comment by larspalo** [comment]
Thanks for reporting. I'm downloading the demo version of the sample set now so that I can test it. It will take some time to complete... However, I can already tell that the odf has problems with how it mixes the new panel format with the old style of specifying gui related things in the structural parts. I'll investigate further when the download is completed.

**Comment by larspalo** [comment]
I think I've found the culprit (stop and coupler values were not zero padded as I assumed they would be) and fixed it with a recent commit. If you build GOODF yourself from source you can test it immediately, otherwise you'll have to wait a little until I've fixed another bug and created a new release here on GitHub.

**Comment by William-Purvis** [comment]
On 13/04/2023 22:17, larspalo wrote:
>
> I think I've found the culprit (stop and coupler values were not zero 
> padded as I assumed they would be) and fixed it with a recent commit. 
> If you build GOODF yourself from source you can test it immediately, 
> otherwise you'll have to wait a little until I've fixed another bug 
> and created a new release here on GitHub.
>
> Message ID: ***@***.***>
>
Thanks, Lars, for that - I'm away for the weekend, but I'll rebuild and 
give it a test soon. I presume my copy and paste
to fix the problem will have copied in the shortened form numbers, so I 
will create a new version and test that.

Bill

-- 
+----------------------------------------+
| Bill Purvis                            |
| ***@***.***                   |
+----------------------------------------+
