### ISSUE TITLE
bitmaps for enclosure GUI elements can't be copied to the Swell setter element

### ISSUE THREAD

**Issue by davidgritter** [larspalo/GOODF#33]
In creating a Gui panel enclosure elements represented by pedals or lighted indicators have as set of up to 127 bitmaps assigned to them.  In a previous release of GOODF you made it possible to right click on the gui element and copy the bitmap to another panel and/or GUI element.  This work enclosure to enclosure element, but not from enclosure to Swell element or from Swell element to enclosure element.  However in most organs with a Crescendo, the pedal and indicator bitmaps for enclosures and Crescendos are the same.  This is not necessarily a bug, but is a feature that should be consistent.

**Comment by larspalo** [comment]
Right. At the moment only elements with exactly the same Type will be possible to copy from/to. Perhaps it would be good to change this behaviour so that it would be possible to copy from/to any element that share the same basic gui element type? Besides allowing to copy between Enclosure and Swell, all kind of buttons that anyway share the same panel could then be targeted from any other button.

**Comment by larspalo** [comment]
With bad7bcdff69830e5e3d9c9594aa950efe5f4dd4d it should now be possible to copy to any matching base type of element, not just the exact same type. Please test and report if it solves the issue.

**Comment by davidgritter** [comment]
Yes, this is working as described.  I tested successfully by copying from an enclosure gui element to a swell gui element, and from a switch gui element to a tremulant gui element.  I also note that other setter elements that derive from button (such as General Cancel) also appear in the list  when copying from a switch gui element but I didn't test that.
