### ISSUE TITLE
unable to set a DispLabelText=<empty> for GUI Elements 

### ISSUE THREAD

**Issue by MStraeten** [larspalo/GOODF#58]
if the DispLabelText is empty in an imported odf its removed on writing, so if the Gui elemt ist displayed via an image, the name is written overlaying the image.
There's no way to define a DispLabelText=<empty> statement.

**Comment by larspalo** [comment]
@MStraeten Right, because it's never supposed to be set like that in the first place. The correct way to **not** display text for an element is to set the TextBreakWidth to zero (TextBreakWidth=0). The DispLabelText should only be used to replace the string normally displayed from the Name property (not to hide it), and to really be valid it should have a value and not be empty. It's actually a bug (for instance in OdfEdit) and it will be fixed https://github.com/GrandOrgue/OdfEdit/issues/29.

From the GrandOrgue help:

```
TextBreakWidth
(integer 0 - text rectangle width, default: slightly smaller than TextWidth) If 0, no text is displayed. Otherwise the value specifies the maximum line width used for text breaking. 
```

**Comment by MStraeten** [comment]
thanks for the hint
